# Generated by Django 2.2.7 on 2019-11-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('emailID', models.CharField(max_length=128, unique=True)),
                ('mobileNo', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
