# Generated by Django 2.2.7 on 2019-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191121_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('img_url', models.CharField(max_length=10000)),
                ('img', models.ImageField(upload_to='assests')),
                ('price', models.FloatField(default=0.0)),
                ('offer', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='emailID',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
