# Generated by Django 2.2.7 on 2019-12-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191210_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='specialofferpercentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='specialprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
