# Generated by Django 2.2.7 on 2019-12-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191210_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
